
[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"
PLAYWRIGHT_BROWSERS_PATH = "0"

[[redirects]]
from = "/2025_moegobff_sz/src"
to = "https://github.com/Doctor-wu/talks/tree/main/talks/2025/moegobff_sz"
status = 302

[[redirects]]
from = "/talks/2025/moegobff_sz"
to = "https://talks.doctorwu.me/2025_moegobff_sz/"
status = 301

[[redirects]]
from = "/2025_moegobff_sz/*"
to = "/2025_moegobff_sz/index.html"
status = 200

[[redirects]]
from = "/2025_conf_vue/pdf"
to = "https://github.com/Doctor-wu/talks/blob/main/talks/2025/vueconf_sz/conf_vue2025.pdf?raw=true"
status = 302

[[redirects]]
from = "/talks/2025/vueconf_sz/pdf"
to = "https://github.com/Doctor-wu/talks/blob/main/talks/2025/vueconf_sz/conf_vue2025.pdf?raw=true"
status = 302

[[redirects]]
from = "/2025_conf_vue/src"
to = "https://github.com/Doctor-wu/talks/tree/main/talks/2025/vueconf_sz"
status = 302

[[redirects]]
from = "/talks/2025/vueconf_sz"
to = "https://talks.doctorwu.me/2025_conf_vue/"
status = 301

[[redirects]]
from = "/2025_conf_vue/*"
to = "/2025_conf_vue/index.html"
status = 200

[[redirects]]
from = "/"
to = "https://doctorwu.me/talks"
status = 302
